version: '3.7'

services:
  workspace:
    volumes:
      - ./:/var/www/app
    build:
      context: ./
      dockerfile: ${PHP_PATH_HOST}/Dockerfile
    ports:
      - "8086:8080"
    user: 1000:1000 # Без этого контейнер как root запускается
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: crm_store
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    tty: true
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
      - ${NGINX_PATH_HOST}/conf.d/:/etc/nginx/conf.d/
      - ${NGINX_PATH_HOST}/log/:/var/log/nginx/
    ports:
      - ${WEB_HTTP_PORT}:80
    depends_on:
      - workspace
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
