version: '3.7'

services:
  workspace:
    volumes:
      - ./:/var/www/app
    build:
      context: ./
      dockerfile: ${PHP_PATH_HOST}/Dockerfile
    user: 1000:1000 # Без этого контейнер как root запускается
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    tty: true
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
      - ${NGINX_PATH_HOST}/conf.d/:/etc/nginx/conf.d/
      - ${NGINX_PATH_HOST}/log/:/var/log/nginx/
    ports:
      - ${WEB_HTTP_PORT}:80
    depends_on:
      - workspace
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
